title: "Mahsa Massoud"
email: "your-email@example.com"
description: >-
  Machine Learning Researcher | Mila/McGill | Foundation Models, VLMs, LLMs

baseurl: ""  # leave this empty for user GitHub Pages (username.github.io)
url: "https://mahsamassoud.github.io"

twitter_username: ""
github_username: mahsamassoud
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author Sidebar Info
author:
  name: "Mahsa Massoud"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "ML researcher | MSc Mila/McGill | Multimodal Foundation Models, VLMs, LLMs"
  links:
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/your-profile"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mahsamassoud"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/your-profile"
    - label: "CV"
      icon: "fas fa-fw fa-file"
      url: "/assets/files/mahsa_cv.pdf"

# Footer social links
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mahsamassoud"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/your-profile"

# Defaults for pages and posts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Pagination
paginate: 5
paginate_path: /page:num/

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Include these folders in the build
include:
  - _pages
